### ISSUE TITLE
Results seem more like re-ordered names vs variations

### ISSUE THREAD

**Issue by wsiegelman** [bellingcat/name-variant-search#10]
This is a great concept and would be very useful. However, the only variations I see are
- first name, last name 
- first name initial, last name
- last name, first name

Should the tool be called name re-ordering vs variations? I assumed variations would show results like 
Dmytro Firtash or Dmytrii or Dimitry 
Igor Kolomoisky or Ihor or Kolomoiskii or Kolomoisky or Kolomoiskiy
etc. 

And this is a very basic one:
Joe Biden or Joseph Biden

<img width="836" alt="Screen Shot 2023-07-30 at 2 05 36 PM" src="https://github.com/bellingcat/name-variant-search/assets/140974956/92eb7793-6938-4a45-98c4-b9d589f615b6">

<img width="830" alt="Screen Shot 2023-07-30 at 2 06 01 PM" src="https://github.com/bellingcat/name-variant-search/assets/140974956/078e46ea-aa77-49c2-8074-e2ed704b9c69">

**Comment by liliakai** [comment]
Hi @wsiegelman. You're right. There should be more variations included in the result. Rest assured, the current version is only the bare minimum for what might be useful to a researcher, and I hope to add more features to it soon. 😄 

Also, I see you're new to github. Welcome to the world of collaborative software development! I'd like to offer some tips to you and others for contributing to this project, so I wrote them up here: [CONTRIBUTING.md](https://github.com/bellingcat/name-variant-search/blob/main/CONTRIBUTING.md)

Once you've read that, I would encourage you to open a new issue on the alias-generator codebase. There are already a few open issues about alternative spellings, but none with these specific examples or Ukrainian names in general, which would probably be quite useful to many researchers.

**Comment by liliakai** [comment]
We now have Joe -> Joseph and similar in alias-generator 4.0.0.

Follow https://github.com/bellingcat/alias-generator/issues/8 for work on spelling variations.
