### ISSUE TITLE
bug: page cannot be indexed by Google

### ISSUE THREAD

**Issue by msramalho** [bellingcat/name-variant-search#17]

**Comment by liliakai** [comment]
I added description and robots. Let's give googlebot some time to update and see if it improves things.

**Comment by liliakai** [comment]
Also verified the site ownership in google's search console, so if it continues to not be indexed, I can see why in  https://search.google.com/search-console

**Comment by liliakai** [comment]
So googlebot says the page is a "soft 404" which I think is a result of the page doing a load-and-then-render on the client side. The initial page load is just a couple lines of text so Google says... this is an error page or something.

fwiw, it's first or second result on duck duck go. I updated this issue accordingly and will try to get a fix shipped this week.

**Comment by msramalho** [comment]
Does having a static header and only the dynamic rendered after loading solve it?

**Comment by liliakai** [comment]
This is what we have currently and there's even a link, but that's not enough apparently.

<img width="884" alt="Screenshot 2024-01-22 at 09 36 31" src="https://github.com/bellingcat/name-variant-search/assets/1039940/18b11c9b-446b-4ccb-a76e-4e1487be2575">

**Comment by liliakai** [comment]
I configured webpack to omit the standard "defer" attribute from the javascript bundle which should block the initial page render until the script is done loading, at the cost of a few extra microseconds of page load time.

**Comment by msramalho** [comment]
Can you search the google search console access with me?


googling `site:https://bellingcat.github.io/name-variant-search` shows results => it's indexed, just not prominently

I saw this is also important:
```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Maybe some more keywords etc?

**Comment by liliakai** [comment]
I don't *think* viewport should affect SEO, but I added it.

**Comment by msramalho** [comment]
![image](https://github.com/bellingcat/name-variant-search/assets/19508417/66e81402-c845-4974-ab3d-1e21a7224ca1)
it seems to be indexed now
